### ISSUE TITLE
requests.exceptions.ConnectionError  in   ZbxTgDaemon.py

### ISSUE THREAD

**Issue by Besson1412** [ableev/Zabbix-in-Telegram#100]
```
$ sudo python ZbxTgDaemon.py 
Traceback (most recent call last):
  File "ZbxTgDaemon.py", line 215, in <module>
    main()
  File "ZbxTgDaemon.py", line 142, in main
    print tg.get_me()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 58, in get_me
    me = self.http_get(url)
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 32, in http_get
    answer = requests.get(url, proxies=self.proxies)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot×××:×××/getMe (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
``` 

i am using  a browser,  use the code:https://api.telegram.org/bot×××:×××/getMe is right
and i am using a http proxy    in  setting file 
and  the bot in alarm is normal

please help. thanks.

**Comment by ableev** [comment]
@Besson1412 what do you mean by "i am using a browser"? 
Is everything ok with your environment?
