### ISSUE TITLE
KeyError: 'message'

### ISSUE THREAD

**Issue by Diko6raz** [ableev/Zabbix-in-Telegram#116]
Hello!
When i press the buttons of the interactive bot, i get an error:
```
{"message": {"from": {"username": "diko6raz", "first_name": "\u0414\u043c\u0438\u0442\u0440\u0438\u0439", "is_bot": false, "id": 435537698, "language_code": "ru"}, "text": "/triggers", "entities": [{"length": 9, "type": "bot_command", "offset": 0}], "chat": {"username": "diko6raz", "first_name": "\u0414\u043c\u0438\u0442\u0440\u0438\u0439", "type": "private", "id": 435537698}, "date": 1520700842, "message_id": 3949}, "update_id": 859118275}
859118276
Traceback (most recent call last):
  File "ZbxTgDaemon.py", line 215, in <module>
    main()
  File "ZbxTgDaemon.py", line 179, in main
    if m["message"]["from"]["id"] not in zbxtg_settings.zbx_tg_daemon_wl_ids:
KeyError: 'message'

```
and in the presence of active triggers produces a message: "There are no triggers, have a nice day!"

**Comment by ableev** [comment]
@Diko6raz there are a lot of changes in the last commit (right now).
Please, test it.
If you have problems anyway, please, contact ZbxTg telegram group.
