### ISSUE TITLE
socks5 proxy Failed to establish a new connection: [Errno -2] 

### ISSUE THREAD

**Issue by klez22** [ableev/Zabbix-in-Telegram#120]
Hello!
I've done all step in [https://github.com/ableev/Zabbix-in-Telegram/issues/119](url)

root# python -m pip freeze | grep -iE 'sock|req'
PySocks==1.6.8
requests==2.6.0
requests-oauthlib==0.8.0

But not work:

```
Traceback (most recent call last):
  File "./zbxtg.py", line 888, in <module>
    main()
  File "./zbxtg.py", line 800, in main
    tg.send_message(uid, zbxtg_body_text)
  File "./zbxtg.py", line 90, in send_message
    answer = requests.post(url, params=params, proxies=self.proxies)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 108, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot406946492:AAECK3vhk5shj3ssjHJl3n3XzKNgNV9R-Y/sendMessage?text=test%0Atest&disable_notification=False&chat_id=367151835%0A&disable_web_page_preview=False (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x138e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
```

**Comment by asvedru** [comment]
Can be a provider's MITM attack on the DNS, check the IP api.telegram.org.
Must be  149.154.167.220

**Comment by ableev** [comment]
Before raising any issues, please, test your proxy first:
https://github.com/ableev/Zabbix-in-Telegram/wiki/Proxy
