### ISSUE TITLE
ZbxTgDaemon.py stopped working after add 5socks support

### ISSUE THREAD

**Issue by jirafff** [ableev/Zabbix-in-Telegram#121]
Hello !

I upgraded sript to last version and add 5socks configuration to zbxtg_settings.py. After that bot successfuly send alert messages, but ZbxTgDaemon.py stopped working:

 [root@localhost alertscripts]# while true; do python ZbxTgDaemon.py; sleep 1; done
Traceback (most recent call last):
  File "ZbxTgDaemon.py", line 215, in <module>
    main()
  File "ZbxTgDaemon.py", line 142, in main
    print tg.get_me()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 58, in get_me
    me = self.http_get(url)
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 32, in http_get
    answer = requests.get(url, proxies=self.proxies)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Can you help ? Maybe need do some changes in ZbxTgDaemon.py code for support 5socks? Thanks

**Comment by WoozyMasta** [comment]
I confirm the existence of a problem

**Comment by ableev** [comment]
@jirafff @WoozyMasta fixed.
And also the script has been rewritten, so please check it and test. 
Thanks.
