### ISSUE TITLE
send notification with socks proxy

### ISSUE THREAD

**Issue by starlessboi** [ableev/Zabbix-in-Telegram#128]
Hi
I want to send notification with socks proxy,but i got this error:
Traceback (most recent call last):
  File "zbxtg.py", line 892, in <module>
    main()
  File "zbxtg.py", line 771, in main
    uid = tg.get_uid(zbx_to)
  File "zbxtg.py", line 175, in get_uid
    updates = self.get_updates()
  File "zbxtg.py", line 66, in get_updates
    answer = requests.post(url, params=params, proxies=self.proxies)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 305, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 215, in get_connection
    block=self._pool_block)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 259, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 214, in __init__
    'Not supported proxy scheme %s' % self.proxy.scheme
AssertionError: Not supported proxy scheme socks5

I use proxy with user and password authentication.
this pattern: proxy_to_tg = "socks5://user1:password2@hostname:port"
would you please help me to solve the problem.
thanks

**Comment by ableev** [comment]
@starlessboi https://github.com/ableev/Zabbix-in-Telegram/wiki/Proxy

**Comment by starlessboi** [comment]
Hi
the problem was because of version of request package, finally i managed to upgrade it...now it's working
thanks for your great job
