### ISSUE TITLE
UnboundLocalError: local variable 'chat' referenced before assignment

### ISSUE THREAD

**Issue by ableev** [ableev/Zabbix-in-Telegram#129]
sudo -u zabbix /usr/lib/zabbix/alertscripts/zbxtg.py "@eermolaeva" test test
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 892, in <module>
    main()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 771, in main
    uid = tg.get_uid(zbx_to)
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 181, in get_uid
    if chat["type"] == self.type == "private":
UnboundLocalError: local variable 'chat' referenced before assignment

**Comment by ableev** [comment]
Probably fixed
