### ISSUE TITLE
Zabbix перестал отправлять уведомления

### ISSUE THREAD

**Issue by alexey-2000** [ableev/Zabbix-in-Telegram#167]
Добрый день.

Сначала все работало как часы. С определенного момента уведомления прекратились. При дебаге показывает следующую ошибку:

Failed to execute command "/usr/lib/zabbix/alertscripts/zbxtg.py '@xxx' '{{Average}} FAIL: Swap usage is too high on Сервер on Сервер' 'Last value: 3193.35351 (09:56:23)
zbxtg;graphs
zbxtg;graphs_period=10800
zbxtg;itemid:114772
zbxtg;title:Сервер - Swap usage is too high on Сервер
zbxtg;single_message' '--debug'": zbxtg.py: {u'ok': True, u'result': {u'username': u'Zabbix_bot', u'first_name': u'Zabbix bot', u'is_bot': True, u'id': XXXXXXXXX}}
zbxtg.py: Cache file with uids: /var/tmp/zbxtg/uids.txt
zbxtg.py: Trying to read cached uid for xxx, private, from /var/tmp/zbxtg/uids.txt
zbxtg.py: Telegram uid of private 'xxx': XXXXXXXX

zbxtg.py: https://zabbix.xxx.ru//chart3.php?period=10800&name=%D0%A1%D0%B5%D1%80%D0%B2%D0%B5%D1%80%20-%20Swap%20usage%20is%20too%20high%20on%20%D0%A1%D0%B5%D1%80%D0%B2%D0%B5%D1%80&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=114772&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00
{u'ok': True, u'result': {u'username': u'Zabbix_bot', u'first_name': u'Zabbix bot', u'is_bot': True, u'id': XXXXXXXX}}
Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 909, in <module>
    main()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 869, in main
    message_id = tg.result["result"]["message_id"]
KeyError: 'message_id'

Заббикс 4. Из шела все отлично отправляет. Картинка по ссылке доступна. Понимаю, что проблема на стороне Заббикса. Подскажите куда копать и что можно предпринять?

Заранее благодарен.

**Comment by alexey-2000** [comment]
После длительных перепроверок стал слать сообщения, но без графиков. При тестирование из шелла выдает следующие ошибки (при подставлении существующего itemid):

sudo -u zabbix ./zbxtg.py amastafyev test "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:65661\nzbxtg;title:ololo')" --debug

zbxtg.py: {u'ok': True, u'result': {u'username': u'jdflsajdljasldjkashdjkhasdbot', u'first_name': u'ZabTest', u'is_bot': True, u'id': 853794445}}
zbxtg.py: Cache file with uids: /var/tmp/zbxtg/uids.txt
zbxtg.py: Trying to read cached uid for amastafyev, private, from /var/tmp/zbxtg/uids.txt
zbxtg.py: Telegram uid of private 'amastafyev': 149513666

zbxtg.py: Trying to /sendMessage:
zbxtg.py: https://api.telegram.org/bot853794445:AAHY0V1I3PZROIruD1F8NyX2aO6EszEQ-VI/sendMessage
zbxtg.py: post params: {'text': 'test', 'disable_notification': False, 'chat_id': '149513666\n', 'disable_web_page_preview': False}
{u'ok': True, u'result': {u'date': 1558449740, u'text': u'test', u'from': {u'username': u'jdflsajdljasldjkashdjkhasdbot', u'first_name': u'ZabTest', u'is_bot': True, u'id': 853794445}, u'message_id': 107, u'chat': {u'username': u'amastafyev', u'first_name': u'Alex', u'type': u'private', u'id': 149513666}}}
zbxtg.py: https://zabbix.test.ru//chart3.php?period=3600&name=ololo&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=65661&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00
zbxtg.py: Trying to /sendPhoto:
zbxtg.py: https://api.telegram.org/bot853794445:AAHY0V1I3PZROIruD1F8NyX2aO6EszEQ-VI/sendPhoto
zbxtg.py: {'caption': '', 'disable_notification': True, 'reply_to_message_id': 107, 'chat_id': '149513666\n', 'reply_markup': '{}'}
zbxtg.py: files: {'photo': <open file '/var/tmp/zbxtg/65661.png', mode 'rb' at 0x7fa764dc1db0>}
Traceback (most recent call last):
  File "./zbxtg.py", line 939, in <module>
    main()
  File "./zbxtg.py", line 917, in main
    tg.send_photo(uid, zbxtg_body_text, zbxtg_file_img)
  File "./zbxtg.py", line 146, in send_photo
    answer = requests.post(url, params=params, files=files, proxies=self.proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
root@c-zab01:/usr/lib/zabbix/alertscripts#

Перед выводом traceback задумывается секунд на 20.
Куда дальше копать?

**Comment by alexey-2000** [comment]
вопрос снят. причина в прокси для телеги.
