### ISSUE TITLE
I cant get Graphs

### ISSUE THREAD

**Issue by arishartono** [ableev/Zabbix-in-Telegram#176]
Today, I have one problem when I do a test ./zbxtg.py arishartono test "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=10800\nzbxtg;itemid:12345\nzbxtg;title:ololo')"

the result is like this

Traceback (most recent call last):
  File "./zbxtg.py", line 939, in <module>
    main()
  File "./zbxtg.py", line 884, in main
    zbx.login()
  File "./zbxtg.py", line 295, in login
    auth=requests.auth.HTTPBasicAuth(self.basic_auth_user, self.basic_auth_pass))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='124.158.174.134', port=80): Max retries exceeded with url: /zabbix// (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75f6a090>: Failed to establish a new connection: [Errno 110] Connection timed out',))

can you help me ?, Thanks You

**Comment by jtprog** [comment]
You can fix. Use 
import urllib3
urllib3.disable_warnings()

**Comment by petqa** [comment]
same issue to me

**Comment by ableev** [comment]
@arishartono it has nothing to do with the script. 
Check your connection.

**Comment by ableev** [comment]
@petqa are you sharing the same server with the topic starter? 
Show your test cases.

**Comment by mcptrishin** [comment]
Hi, I've the same problem. How do you fix it?
