### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by vcont** [ableev/Zabbix-in-Telegram#177]
Hi guys, for the last weeks i have problem to use the script.

 it was working correctly, but is not working anymore.

i tested with the suggested command:
`./zbxtg.py @someaccount  "xyz" "xyz"`

and the result is the following error:

```
Traceback (most recent call last):
  File "./zbxtg_group.py", line 939, in <module>
    main()
  File "./zbxtg_group.py", line 848, in main
    tg.send_message(uid, zbxtg_body_text)
  File "./zbxtg_group.py", line 94, in send_message
    answer = requests.post(url, params=params, proxies=self.proxies)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
```

**Comment by ableev** [comment]
The reason for it is your internet provider, check connectivity to the Telegram Bot API server.

**Comment by vcont** [comment]
I'm sorry, I didn't have any chance at the weekend to update this ticket.

> The reason for it is your internet provider, check connectivity to the Telegram Bot API server.

indeed, the problem was in the network. The firewall is performing DPI to HTTPS and the certificates were missing on the server. Thanks for the quickly reponse.
