### ISSUE TITLE
unable to run test

### ISSUE THREAD

**Issue by unnilennium** [ableev/Zabbix-in-Telegram#179]
after installing according to Readme, I tried the test as shown in the wiki:

`# sudo -u zabbix ./zbxtg.py "@jppialasse"
Traceback (most recent call last):
  File "./zbxtg.py", line 9, in <module>
    import requests
  File "/usr/lib/python2.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python2.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
`
# python --version
Python 2.6.6
[root@backbench bin]# pip --version
pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)

**Comment by helipopolis** [comment]
Need Python 2.7

**Comment by unnilennium** [comment]
thanks for the info, could you add it in the Readme to avoid confusion?

I am using a old CentOs 6, after removing requirements using pip and reinstalling using yum I got it working:

```
pip uninstall requests requests-oauthlib PySocks urllib3 chardet
yum install  python2-pysocket python-requests python-requests-oauthlib --enablerepo=epel
```
then test message was working

alternatively I would have tried software collection packages for python27 and made a wrapper to enable sclo before calling the script.

worked fine without the sclo
