### ISSUE TITLE
add retry sending

### ISSUE THREAD

**Issue by wulfgar93** [ableev/Zabbix-in-Telegram#185]
Hello! 

I use socks5h proxy and sometimes I retrieve error:
```
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 939, in <module>
main()
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 848, in main
tg.send_message(uid, zbxtg_body_text)
File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 94, in send_message
answer = requests.post(url, params=params, proxies=self.proxies)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 116, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

Can you add retry for message sending please?

**Comment by ableev** [comment]
Zabbix has such functionality and it's working.

**Comment by wulfgar93** [comment]
@ableev could you explain where am I can set up this functionality in Zabbix?

**Comment by coeus-lei** [comment]
The error  is send by your socks5h proxy  I think so!!
