### ISSUE TITLE
I can't get Graphs

### ISSUE THREAD

**Issue by mcptrishin** [ableev/Zabbix-in-Telegram#204]
HI, I can't get Graphs.

Try by testing script
 ./zbxtg.py xxxxxxx test "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:12345\nzbxtg;title:ololo')"
then I get
Traceback (most recent call last):
  File "./zbxtg.py", line 940, in <module>
    main()
  File "./zbxtg.py", line 885, in main
    zbx.login()
  File "./zbxtg.py", line 295, in login
    auth=requests.auth.HTTPBasicAuth(self.basic_auth_user, self.basic_auth_pass))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /zabbix// (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2f6f6c8d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

But I get message in telegram without Graphs.

**Comment by mcptrishin** [comment]
Sorry, may be closed
