### ISSUE TITLE
Zabbix 5.4 graphs not working after update

### ISSUE THREAD

**Issue by dramatic-prophet** [ableev/Zabbix-in-Telegram#209]
Hello. We updated our zabbix from 4.4 to 5.4.3 recently, and after update we got message "Login to Zabbix web UI has failed (web url, user or password are incorrect), unable to send graphs check manually" instead of graphs in telegram. 

In nginx error log I see folowing error:

`2021/08/13 16:29:31 [error] 472#472: *3003743 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strrpos() expects parameter 1 to be string, bool given in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php:72
Stack trace:
#0 /usr/share/zabbix/include/classes/helpers/CCookieHelper.php(72): strrpos(false, '/')
#1 /usr/share/zabbix/include/classes/core/CCookieSession.php(126): CCookieHelper::set('zbx_session', 'eyJzZXNzaW9uaWQ...', 0)
#2 [internal function]: CCookieSession->write('beb5b71f4777fa3...', 'eyJzZXNzaW9uaWQ...')
#3 {main}
  thrown in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php on line 72PHP message: PHP Warning:  Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0" while reading response header from upstream, client: 10.7.1.141, server: 10.7.1.141, request: "POST // HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "dash.cosmonova.corp"
2021/08/13 16:29:31 [error] 472#472: *3003743 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: strrpos() expects parameter 1 to be string, null given in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php:72
Stack trace:
#0 /usr/share/zabbix/include/classes/helpers/CCookieHelper.php(72): strrpos(NULL, '/')
#1 /usr/share/zabbix/include/classes/core/CCookieSession.php(126): CCookieHelper::set('zbx_session', 'eyJzZXNzaW9uaWQ...', 0)
#2 [internal function]: CCookieSession->write('85782301c45cd1b...', 'eyJzZXNzaW9uaWQ...')
#3 /usr/share/zabbix/include/func.inc.php(1552): session_write_close()
#4 /usr/share/zabbix/include/classes/mvc/CController.php(388): access_deny(1)
#5 /usr/share/zabbix/include/classes/core/ZBase.php(562): CController->run()
#6 /usr/share/zabbix/include/classes/core/ZBase.php(214): ZBase->processRequest(Object(CRouter))
#7 /usr/share/zabbix/include/config.inc.php(25): ZBase->run('default')
#8 /usr/share/zabbix/zabbix.php(22): require_once('/usr/share/zabb...')
#9 {main}
  thrown in /usr/share/zabbix/include/classes/he" while reading response header from upstream, client: 10.7.1.141, server: 10.7.1.141, request: "GET //zabbix.php?action=dashboard.view HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "dash.cosmonova.corp"
`

It happens only with telegram script. Web access with browser and same account, that bot uses, works just fine. Also API login with bot account also works fine. 
Got any advice?

**Comment by dramatic-prophet** [comment]
Moved environment to python3 from python2, problem solved itself.
