### ISSUE TITLE
Error when sending notifications from Zabbix Server 7.0.3

### ISSUE THREAD

**Issue by SD3vEng** [ableev/Zabbix-in-Telegram#220]
OS: Oracle Linux 9.4 Python 3.9 Zabbix Server 7.0.3
Good afternoon! I use your script to send messages in telegrams. When inserting messages with the following parameters into the template, if you remove the graph, what is sent without an error :
`zbxtg;graphs
zbxtg;graphs_period=3600
Начало проблемы: {EVENT.TIME} on {EVENT.DATE}
Problem name: {EVENT.NAME}
Host: {HOST.NAME}
Severity: {EVENT.SEVERITY}
Operational data: {EVENT.OPDATA}
Original problem ID: {EVENT.ID}`
![image](https://github.com/user-attachments/assets/027b852b-a97d-4035-846f-bea6a7fb6368)

An error message appears, but the text part of the alert notification is sent in telegrams, without graphs:
`Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 940, in <module>
    main()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 893, in main
    zbxtg_file_img = zbx.graph_get(settings["zbxtg_itemid"], settings["zbxtg_image_period"],
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 310, in graph_get
    title = requests.utils.quote(title)
  File "/usr/lib64/python3.9/urllib/parse.py", line 883, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib64/python3.9/urllib/parse.py", line 908, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes`

**Comment by AVBaranov93** [comment]
Hi. Did you solve this problem ? I get similar error. Can get only text  part of the message without graphs (

**Comment by ivanmirandaf** [comment]
I also have the same problem in Zabbix 7.
Zabbix 6 is working normally.
