### ISSUE TITLE
Error JSON Code

### ISSUE THREAD

**Issue by augustoferronato** [ableev/Zabbix-in-Telegram#31]
When run in debug mode, this error is displayed

Traceback (most recent call last):
  File "./zbxtg.py", line 398, in <module>
    main()
  File "./zbxtg.py", line 295, in main
    print_message(tg.get_me())
  File "./zbxtg.py", line 35, in get_me
    me = self.http_get(url)
  File "./zbxtg.py", line 21, in http_get
    answer_json = json.loads(answer)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

According the google, can be the encoding from JSON, using Zabbix 3.0.1

Python 2.7

**Comment by thuekx** [comment]
I think i have the same issued,
i try command line, and run into this 
./zbxtg.py "@thuekx" tes tes
Traceback (most recent call last):
  File "./zbxtg.py", line 398, in <module>
    main()
  File "./zbxtg.py", line 352, in main
    uid = tg.get_uid(zbx_to)
  File "./zbxtg.py", line 92, in get_uid
    updates = self.get_updates()
  File "./zbxtg.py", line 42, in get_updates
    updates = self.http_get(url)
  File "./zbxtg.py", line 21, in http_get
    answer_json = json.loads(answer)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by augustoferronato** [comment]
The problem for me as solved you can't start the bot, before run the script. Create the bot (botfather), put the API on the settings and try (not start a chat with your bot).

**Comment by thuekx** [comment]
So i must create another bot? or i can use my first bot created?

can u give me a step by step to run the script ? 

because before i "/start" the bot i make sure that Api user and password has been inserted correctly into setting, or any other step to make sure the script running?

thank you for the answered

**Comment by ableev** [comment]
@thuekx @augustoferronato can you join public group https://telegram.me/ZbxTg and describe you problem with more details.
You provide traceback without any reproduce case, how am I supposed to fix it?
Thanks.

**Comment by thuekx** [comment]
This is issued has been solvedn group by ilya 

if you get that error, please double check your script or just download the last script from github only

Thank you @ableev

**Comment by ableev** [comment]
@augustoferronato if you have any troubles, contact us in group chat. I can't reproduce your problem.
