### ISSUE TITLE
Upload Photo doesn't work

### ISSUE THREAD

**Issue by Xell79** [ableev/Zabbix-in-Telegram#39]
Photo uploading doesn't work since today. Tried dev branch with no luck.
 ./zbxtg.py $username graph "$(echo -e 'zbxtg;graphs: \nzbxtg;graphs_period=3600\nzbxtg;itemid:34876\nzbxtg;title:graph')" --debug
zbxtg.py: {u'ok': True, u'result': {u'username': u'$name_bot', u'first_name': u'$namemon', u'id': $id}}
zbxtg.py: Cache file with uids: /tmp/zbxtg/uids.txt
zbxtg.py: Telegram uid of private '$username': $id

zbxtg.py: http://dcm1-mon/zabbix/chart3.php?period=3600&name=graph&width=900&height=200&graphtype=0&legend=1&items[0][itemid]=34876&items[0][sortorder]=0&items[0][drawtype]=5&items[0][color]=00CC00
zbxtg.py: Trying to /sendMessage:
zbxtg.py: https://api.telegram.org/bot$/sendMessage
zbxtg.py: post params: {'text': 'graph', 'disable_notification': False, 'chat_id': '$id\n', 'disable_web_page_preview': False}
zbxtg.py: Post is Ok
zbxtg.py: Trying to /sendPhoto:
zbxtg.py: https://api.telegram.org/bot$/sendPhoto
zbxtg.py: {'caption': '', 'disable_notification': True, 'chat_id': '$id\n', 'reply_to_message_id': 3889}
zbxtg.py: files: {'photo': <open file '/tmp/zbxtg/34876.png', mode 'rb' at 0x7fe10786fb70>}
Traceback (most recent call last):
  File "./zbxtg.py", line 450, in <module>
    main()
  File "./zbxtg.py", line 445, in main
    if tg.send_photo(uid, zbxtg_body_text, zbxtg_file_img):
  File "./zbxtg.py", line 95, in send_photo
    res = requests.post(url, params=params, files=files, proxies=self.proxies)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 608, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/models.py", line 737, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by ableev** [comment]
@Xell79 looks like something new. Could you, please, contact me directly and help me to solve that error? Thanks.
