### ISSUE TITLE
Update Zabbix 3.4.1

### ISSUE THREAD

**Issue by brutevinch** [ableev/Zabbix-in-Telegram#82]
After update zbxtg.py stops working.

this works fine:
`~ # python /usr/lib/zabbix/alertscripts/zbxtg.py "Дом" ololo ololo --group
`
but when it runs under Zabbix in debug I see this:
```
 26963:20170830:221817.785 Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 458, in <module>
    main()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 428, in main
    zbx.login()
  File "/usr/lib/zabbix/alertscripts/zbxtg.py", line 166, in login
    req_cookie = requests.post(self.server + "/", data=data_api, proxies=self.proxies, verify=self.verify)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(113, 'No route to host'))
```

**Comment by ableev** [comment]
@brutevinch join group chat ZbxTg and provide more info.
Other guys don't see any problems after upgrading to 3.4.

P.S. No route to host seems to be network problem.
