### ISSUE TITLE
Dev branch. New file uids.txt not created after removing an old file.

### ISSUE THREAD

**Issue by Varrkan82** [ableev/Zabbix-in-Telegram#89]
If an uids.txt file is missed in a some reason - the new file can not be created.
I've got an error while running script in a console:
<code>
Traceback (most recent call last):                                                   File "./zbxtg.py", line 859, in <module>                                             main()                                                                           File "./zbxtg.py", line 743, in main                                                 uid = tg.get_uid(zbx_to)                                                         File "./zbxtg.py", line 181, in get_uid                                              if chat["type"] == self.type == "private":                                     UnboundLocalError: local variable 'chat' referenced before assignment
</code>

Maybe it could be in a reason of I'm using a private groupe usually.
Also a new uid can't be added to a present uids.txt file with a same error.

I'm not tested it with a master branch.

UPD: The same error is in a #81 issue.

**Comment by Varrkan82** [comment]
The fix from a pull request in a #81 is helps.

**Comment by ableev** [comment]
@Varrkan82 please, provide the reproduce case

**Comment by Varrkan82** [comment]
@ableev it's strange, but I can't reproduce it's by myself now... Sorry. Close the issue. Thanks/

**Comment by ableev** [comment]
@Varrkan82 I commented in the related issue, it was fixed long time ago. And if it's appears now, I can't imagine how could it be :)
