### ISSUE TITLE
ZbxTgDaemon.py stopped and not starting after receiving a command from a private group.

### ISSUE THREAD

**Issue by Varrkan82** [ableev/Zabbix-in-Telegram#94]
After receiving a command from a private group the daemon is stopped and not starting again.

`root@vmh1000 /home/zabbix/bin # sudo -u zabbix python ZbxTgDaemon.py               {u'ok': True, u'result': {u'username': u'nXXXXXXbot', u'first_name': u'zabbix_bot', u'is_bot': True, u'id': 000000000}}                                                14d1ee10f78000000001218c0000067b                                                   Traceback (most recent call last):                                                   File "ZbxTgDaemon.py", line 221, in <module>                                         main()                                                                           File "ZbxTgDaemon.py", line 176, in main                                             print m["message"]["from"]["id"]                                               KeyError: 'message'`
`
Credentials are modified in example for a security reaction.

**Comment by ableev** [comment]
@Varrkan82 seems like an old error, and I've fixed it already
```
flashpoint:Zabbix-in-Telegram lost$ git diff ZbxTgDaemon.py | wc -l
     413
```
Will try to push changes, sorry.
